version: '3'

services:

  suncity_xlsx_module:
    build:
      context: ..
      dockerfile: Dockerfile-dev
    container_name: suncity_xlsx_module
    ports:
      - "8080:80"
    volumes:
      - ..:/home/docker/code
      - ./local_data/logs:/var/logs
    environment:
      - ENV=develop
      - BACKEND_URL=http://suncity-backend.worklize.com
    networks:
      - qrcode

networks:
  qrcode:
